@WebAPI_HostAddress = http://localhost:5156

###

POST @WebAPI_HostAddress/posts
Content-Type: application/json

{
  "Title": "My First Post",
  "Content": "This is the content of my first post.",
  "AuthorId": 1
}